In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn import tree
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt

In [2]:
train_t = pd.read_csv('train.csv')
train_t.head()

time_in_hospital  num_lab_procedures  num_procedures  num_medications  \
0         -0.784698            0.292344       -0.247341        -0.579531   
1          0.229955            0.292344       -0.816030        -1.302427   
2          0.568172            0.092308        1.458724        -0.097600   
3          1.582825            0.442371       -0.247341         0.022883   
4          3.273913           -1.107909       -0.816030        -0.097600   

   number_outpatient  number_emergency  number_inpatient  number_diagnoses  \
0          -0.261276         -0.206332         -0.302125         -2.300532   
1          -0.261276         -0.206332         -0.302125         -2.300532   
2          -0.261276         -0.206332          2.922323         -0.712431   
3          -0.261276         -0.206332         -0.302125          0.875671   
4           2.465632          1.693810          2.922323         -0.183063   

   readmitted         x       ...           x.6.3    x.13.1     x.3.5  \
0         NaN -0.474839       ...       -1.086339 -0.274604 -0.254056   
1         NaN  2.105940       ...        0.920506 -0.274604 -0.254056   
2         NaN  2.105940       ...        0.920506 -0.274604 -0.254056   
3         NaN -0.474839       ...       -1.086339 -0.274604 -0.254056   
4         NaN -0.474839       ...       -1.086339 -0.274604 -0.254056   

      x.8.3    x.11.2    x.18.1      x.72     x.263    x.276  training_label  
0 -0.262402 -0.278155 -0.422036 -0.967392 -0.282538 -0.24487               3  
1 -0.262402 -0.278155  2.369422 -0.967392 -0.282538 -0.24487               3  
2 -0.262402 -0.278155 -0.422036 -0.967392 -0.282538 -0.24487               2  
3 -0.262402 -0.278155  2.369422 -0.967392 -0.282538 -0.24487               3  
4 -0.262402 -0.278155 -0.422036  1.033688 -0.282538 -0.24487               2  

[5 rows x 36 columns]

In [3]:
np.unique(train_t['training_label'],return_counts=True)

(array([1, 2, 3]), array([ 4901, 17300, 32704]))

In [4]:
test_t = pd.read_csv('test.csv')
test_t.head()

time_in_hospital  num_lab_procedures  num_procedures  num_medications  \
0         -0.785344           -0.657165        2.577013        -0.097341   
1         -1.122811           -1.656848        0.312642        -1.301251   
2          0.227060           -0.107339       -0.819543         0.384223   
3          0.227060            0.142582       -0.819543        -0.819687   
4          1.914400           -0.307275        2.010921         0.023050   

   number_outpatient  number_emergency  number_inpatient  number_diagnoses  \
0          -0.267341         -0.225309         -0.302265          0.875792   
1          -0.267341         -0.225309         -0.302265         -1.246853   
2          -0.267341          1.913455         -0.302265          0.875792   
3          -0.267341         -0.225309         -0.302265         -1.777515   
4          -0.267341          1.913455         -0.302265         -0.716192   

          x       x.2     ...         x.6.3    x.13.1     x.3.5     x.8.3  \
0  2.105173 -1.829516     ...      0.922331 -0.274221 -0.253365 -0.263471   
1 -0.475012  0.546583     ...     -1.084190 -0.274221 -0.253365 -0.263471   
2  2.105173 -1.829516     ...     -1.084190 -0.274221 -0.253365 -0.263471   
3 -0.475012  0.546583     ...     -1.084190 -0.274221 -0.253365 -0.263471   
4  2.105173 -1.829516     ...      0.922331 -0.274221 -0.253365 -0.263471   

     x.11.2    x.18.1      x.72     x.263     x.276  test_label  
0 -0.276135 -0.421407  1.030376  3.553004 -0.244912           3  
1 -0.276135 -0.421407  1.030376  3.553004 -0.244912           3  
2 -0.276135  2.372959 -0.970501 -0.281447 -0.244912           3  
3 -0.276135 -0.421407  1.030376 -0.281447 -0.244912           3  
4 -0.276135  2.372959 -0.970501 -0.281447 -0.244912           3  

[5 rows x 35 columns]

In [5]:
np.unique(test_t['test_label'],return_counts=True)

(array([1, 2, 3]), array([ 131, 3600, 9800]))

In [6]:
fk = dict()
for k in test_t:
    fk[k] = 1
    print k,

time_in_hospital num_lab_procedures num_procedures num_medications number_outpatient number_emergency number_inpatient number_diagnoses x x.2 x.716 x.1.1 x.4.1 x.5 x.6 x.7 x.8 x.718 x.1.3 x.2.3 x.5.1 x.719 x.2.4 x.5.2 x.720 x.6.3 x.13.1 x.3.5 x.8.3 x.11.2 x.18.1 x.72 x.263 x.276 test_label


In [7]:
for k in test_t:
    print k,fk[k]

time_in_hospital 1
num_lab_procedures 1
num_procedures 1
num_medications 1
number_outpatient 1
number_emergency 1
number_inpatient 1
number_diagnoses 1
x 1
x.2 1
x.716 1
x.1.1 1
x.4.1 1
x.5 1
x.6 1
x.7 1
x.8 1
x.718 1
x.1.3 1
x.2.3 1
x.5.1 1
x.719 1
x.2.4 1
x.5.2 1
x.720 1
x.6.3 1
x.13.1 1
x.3.5 1
x.8.3 1
x.11.2 1
x.18.1 1
x.72 1
x.263 1
x.276 1
test_label 1


In [8]:
test_t.head()

time_in_hospital  num_lab_procedures  num_procedures  num_medications  \
0         -0.785344           -0.657165        2.577013        -0.097341   
1         -1.122811           -1.656848        0.312642        -1.301251   
2          0.227060           -0.107339       -0.819543         0.384223   
3          0.227060            0.142582       -0.819543        -0.819687   
4          1.914400           -0.307275        2.010921         0.023050   

   number_outpatient  number_emergency  number_inpatient  number_diagnoses  \
0          -0.267341         -0.225309         -0.302265          0.875792   
1          -0.267341         -0.225309         -0.302265         -1.246853   
2          -0.267341          1.913455         -0.302265          0.875792   
3          -0.267341         -0.225309         -0.302265         -1.777515   
4          -0.267341          1.913455         -0.302265         -0.716192   

          x       x.2     ...         x.6.3    x.13.1     x.3.5     x.8.3  \
0  2.105173 -1.829516     ...      0.922331 -0.274221 -0.253365 -0.263471   
1 -0.475012  0.546583     ...     -1.084190 -0.274221 -0.253365 -0.263471   
2  2.105173 -1.829516     ...     -1.084190 -0.274221 -0.253365 -0.263471   
3 -0.475012  0.546583     ...     -1.084190 -0.274221 -0.253365 -0.263471   
4  2.105173 -1.829516     ...      0.922331 -0.274221 -0.253365 -0.263471   

     x.11.2    x.18.1      x.72     x.263     x.276  test_label  
0 -0.276135 -0.421407  1.030376  3.553004 -0.244912           3  
1 -0.276135 -0.421407  1.030376  3.553004 -0.244912           3  
2 -0.276135  2.372959 -0.970501 -0.281447 -0.244912           3  
3 -0.276135 -0.421407  1.030376 -0.281447 -0.244912           3  
4 -0.276135  2.372959 -0.970501 -0.281447 -0.244912           3  

[5 rows x 35 columns]

In [9]:
y_train = train_t['training_label'].as_matrix()
y_train

array([3, 3, 2, ..., 3, 2, 3])

In [10]:
for k in train_t:
    if k == "training_label":
        print k
        continue
    if fk.has_key(k):
        print k
        continue
    else:
        print k,"J"
        del train_t[k]
print 
for k in train_t:
    print k,

time_in_hospital
num_lab_procedures
num_procedures
num_medications
number_outpatient
number_emergency
number_inpatient
number_diagnoses
readmitted J
x
x.2
x.716
x.1.1
x.4.1
x.5
x.6
x.7
x.8
x.718
x.1.3
x.2.3
x.5.1
x.719
x.2.4
x.5.2
x.720
x.6.3
x.13.1
x.3.5
x.8.3
x.11.2
x.18.1
x.72
x.263
x.276
training_label

time_in_hospital num_lab_procedures num_procedures num_medications number_outpatient number_emergency number_inpatient number_diagnoses x x.2 x.716 x.1.1 x.4.1 x.5 x.6 x.7 x.8 x.718 x.1.3 x.2.3 x.5.1 x.719 x.2.4 x.5.2 x.720 x.6.3 x.13.1 x.3.5 x.8.3 x.11.2 x.18.1 x.72 x.263 x.276 training_label


In [11]:
train_t.head()

time_in_hospital  num_lab_procedures  num_procedures  num_medications  \
0         -0.784698            0.292344       -0.247341        -0.579531   
1          0.229955            0.292344       -0.816030        -1.302427   
2          0.568172            0.092308        1.458724        -0.097600   
3          1.582825            0.442371       -0.247341         0.022883   
4          3.273913           -1.107909       -0.816030        -0.097600   

   number_outpatient  number_emergency  number_inpatient  number_diagnoses  \
0          -0.261276         -0.206332         -0.302125         -2.300532   
1          -0.261276         -0.206332         -0.302125         -2.300532   
2          -0.261276         -0.206332          2.922323         -0.712431   
3          -0.261276         -0.206332         -0.302125          0.875671   
4           2.465632          1.693810          2.922323         -0.183063   

          x       x.2       ...           x.6.3    x.13.1     x.3.5     x.8.3  \
0 -0.474839  0.545430       ...       -1.086339 -0.274604 -0.254056 -0.262402   
1  2.105940 -1.833381       ...        0.920506 -0.274604 -0.254056 -0.262402   
2  2.105940 -1.833381       ...        0.920506 -0.274604 -0.254056 -0.262402   
3 -0.474839  0.545430       ...       -1.086339 -0.274604 -0.254056 -0.262402   
4 -0.474839  0.545430       ...       -1.086339 -0.274604 -0.254056 -0.262402   

     x.11.2    x.18.1      x.72     x.263    x.276  training_label  
0 -0.278155 -0.422036 -0.967392 -0.282538 -0.24487               3  
1 -0.278155  2.369422 -0.967392 -0.282538 -0.24487               3  
2 -0.278155 -0.422036 -0.967392 -0.282538 -0.24487               2  
3 -0.278155  2.369422 -0.967392 -0.282538 -0.24487               3  
4 -0.278155 -0.422036  1.033688 -0.282538 -0.24487               2  

[5 rows x 35 columns]

In [12]:
y_train = y_train -1
y_train

array([2, 2, 1, ..., 2, 1, 2])

In [13]:
print(np.unique(y_train,return_counts=True))

(array([0, 1, 2]), array([ 4901, 17300, 32704]))


In [14]:
del train_t['training_label']
X_train = train_t.as_matrix()
X_train.shape

(54905, 34)

In [15]:
y_test = test_t['test_label'].as_matrix()
y_test

array([3, 3, 3, ..., 1, 1, 1])

In [16]:
y_test = y_test -1
y_test

array([2, 2, 2, ..., 0, 0, 0])

In [17]:
print(np.unique(y_test,return_counts=True))

(array([0, 1, 2]), array([ 131, 3600, 9800]))


In [18]:
del test_t['test_label']
X_test = test_t.as_matrix()
X_test.shape

(13531, 34)

In [32]:
from sklearn.metrics import accuracy_score
import time
clf = LogisticRegression(C=1,tol=0.0000001,fit_intercept=True,class_weight='balanced',intercept_scaling=2.0,dual=True)
old_ticks = time.time()
clf.fit(X_train,y_train)
new_ticks = time.time()
print new_ticks - old_ticks
old_ticks = time.time()
pred = clf.predict(X_test)
new_ticks = time.time()
print new_ticks - old_ticks
accuracy_score(pred,y_test)

15.061809063
0.00432705879211


0.67607715615992903

In [29]:
clf1 = tree.DecisionTreeClassifier(min_samples_leaf=25)
old_ticks = time.time()
clf1.fit(X_train,y_train)
new_ticks = time.time()
print new_ticks - old_ticks
old_ticks = time.time()
pred1 = clf1.predict(X_test)
new_ticks = time.time()
print new_ticks - old_ticks
accuracy_score(pred1,y_test)

0.764183044434
0.00631403923035


0.71753750646663217

In [33]:
clf2 = RandomForestClassifier(min_samples_leaf=25,max_depth=25)
old_ticks = time.time()
clf2.fit(X_train,y_train)
new_ticks = time.time()
print new_ticks - old_ticks
old_ticks = time.time()
pred2 = clf2.predict(X_test)
new_ticks = time.time()
print new_ticks - old_ticks
accuracy_score(pred2,y_test)

1.1047680378
0.0542619228363


0.73475722415194733

In [ ]:
from sklearn import svm
clf3s = svm.SVC(kernel='rbf')
old_ticks = time.time()
clf3s.fit(X_train,y_train)
new_ticks = time.time()
print new_ticks - old_ticks
old_ticks = time.time()
pred3 = clf3s.predict(X_test)
new_ticks = time.time()
print new_ticks - old_ticks
accuracy_score(pred3,y_test)

In [34]:
y_t = []
for k in y_train:
    ys = [0,0,0]
    ys[k] = 1
    y_t.append(ys)

y_te = []
for k in y_test:
    ys = [0,0,0]
    ys[k] = 1
    y_te.append(ys)
y_t = np.array(y_t)
y_te = np.array(y_te)
print y_t.shape
print y_te.shape

(54905, 3)
(13531, 3)


In [38]:
import tensorflow as tf
#from tensorflow.examples.tutorials.mnist import input_data
#mnist = input_data.read_data_sets("/tmp/data/", one_hot = True)

n_nodes_hl1 = 10
n_nodes_hl2 = 5
'''n_nodes_hl3 = 10
n_nodes_hl4 = 10
n_nodes_hl5 = 10
n_nodes_hl6 = 10
n_nodes_hl7 = 10
n_nodes_hl8 = 10
n_nodes_hl9 = 10
n_nodes_hl10 = 10
n_nodes_hl11 = 10
n_nodes_hl12 = 10'''

n_classes = 3
batch_size = 79

x = tf.placeholder('float', [None, X_test.shape[1]])
y = tf.placeholder('float')

def neural_network_model(data):
    hidden_1_layer = {'weights':tf.Variable(tf.random_normal([X_test.shape[1], n_nodes_hl1])),
                      'biases':tf.Variable(tf.random_normal([n_nodes_hl1]))}
    hidden_2_layer = {'weights':tf.Variable(tf.random_normal([n_nodes_hl1, n_nodes_hl2])),
                      'biases':tf.Variable(tf.random_normal([n_nodes_hl2]))}
    '''hidden_3_layer = {'weights':tf.Variable(tf.random_normal([n_nodes_hl2, n_nodes_hl3])),
                      'biases':tf.Variable(tf.random_normal([n_nodes_hl3]))}
    hidden_4_layer = {'weights':tf.Variable(tf.random_normal([n_nodes_hl3, n_nodes_hl4])),
                      'biases':tf.Variable(tf.random_normal([n_nodes_hl4]))}
    hidden_5_layer = {'weights':tf.Variable(tf.random_normal([n_nodes_hl4, n_nodes_hl5])),
                      'biases':tf.Variable(tf.random_normal([n_nodes_hl5]))}
    hidden_6_layer = {'weights':tf.Variable(tf.random_normal([n_nodes_hl5, n_nodes_hl6])),
                      'biases':tf.Variable(tf.random_normal([n_nodes_hl6]))}
    hidden_7_layer = {'weights':tf.Variable(tf.random_normal([n_nodes_hl6, n_nodes_hl7])),
                      'biases':tf.Variable(tf.random_normal([n_nodes_hl7]))}
    hidden_8_layer = {'weights':tf.Variable(tf.random_normal([n_nodes_hl7, n_nodes_hl8])),
                      'biases':tf.Variable(tf.random_normal([n_nodes_hl8]))}
    hidden_9_layer = {'weights':tf.Variable(tf.random_normal([n_nodes_hl8, n_nodes_hl9])),
                      'biases':tf.Variable(tf.random_normal([n_nodes_hl9]))}
    hidden_10_layer = {'weights':tf.Variable(tf.random_normal([n_nodes_hl9, n_nodes_hl10])),
                      'biases':tf.Variable(tf.random_normal([n_nodes_hl10]))}
    hidden_11_layer = {'weights':tf.Variable(tf.random_normal([n_nodes_hl10, n_nodes_hl11])),
                      'biases':tf.Variable(tf.random_normal([n_nodes_hl11]))}
    hidden_12_layer = {'weights':tf.Variable(tf.random_normal([n_nodes_hl11, n_nodes_hl12])),
                      'biases':tf.Variable(tf.random_normal([n_nodes_hl12]))}'''
    output_layer = {'weights':tf.Variable(tf.random_normal([n_nodes_hl2, n_classes])),
                    'biases':tf.Variable(tf.random_normal([n_classes])),}


    l1 = tf.add(tf.matmul(data,hidden_1_layer['weights']), hidden_1_layer['biases'])
    l1 = tf.nn.relu(l1)
    l2 = tf.add(tf.matmul(l1,hidden_2_layer['weights']), hidden_2_layer['biases'])
    l2 = tf.nn.relu(l2)
    '''l3 = tf.add(tf.matmul(l2,hidden_3_layer['weights']), hidden_3_layer['biases'])
    l3 = tf.nn.relu(l3)
    l4 = tf.add(tf.matmul(l3,hidden_4_layer['weights']), hidden_4_layer['biases'])
    l4 = tf.nn.relu(l4)
    l5 = tf.add(tf.matmul(l4,hidden_5_layer['weights']), hidden_5_layer['biases'])
    l5 = tf.nn.relu(l5)
    l6 = tf.add(tf.matmul(l5,hidden_6_layer['weights']), hidden_6_layer['biases'])
    l6 = tf.nn.relu(l6)
    l7 = tf.add(tf.matmul(l6,hidden_7_layer['weights']), hidden_7_layer['biases'])
    l7 = tf.nn.relu(l7)
    l8 = tf.add(tf.matmul(l7,hidden_8_layer['weights']), hidden_8_layer['biases'])
    l8 = tf.nn.relu(l8)
    l9 = tf.add(tf.matmul(l8,hidden_9_layer['weights']), hidden_9_layer['biases'])
    l9 = tf.nn.relu(l9)
    l10 = tf.add(tf.matmul(l9,hidden_10_layer['weights']), hidden_10_layer['biases'])
    l10 = tf.nn.relu(l10)
    l11 = tf.add(tf.matmul(l10,hidden_11_layer['weights']), hidden_11_layer['biases'])
    l11 = tf.nn.relu(l11)
    l12 = tf.add(tf.matmul(l11,hidden_12_layer['weights']), hidden_12_layer['biases'])
    l12 = tf.nn.relu(l12)'''
    output = tf.matmul(l2,output_layer['weights']) + output_layer['biases']
    
    return output

def train_neural_network(x):
    prediction = neural_network_model(x)
    # OLD VERSION:
    #cost = tf.reduce_mean( tf.nn.softmax_cross_entropy_with_logits(prediction,y) )
    # NEW:
    cost = tf.reduce_mean( tf.nn.softmax_cross_entropy_with_logits(logits=prediction, labels=y) )
    optimizer = tf.train.AdamOptimizer().minimize(cost)
    
    hm_epochs = 501
    with tf.Session() as sess:
        # OLD:
        #sess.run(tf.initialize_all_variables())
        # NEW:
        sess.run(tf.global_variables_initializer())

        for epoch in range(hm_epochs):
            epoch_loss = 0
            i = 0
            while i < len(X_train):
                start = i
                end = i+batch_size
                batch_x = np.array(X_train[start:end])
                batch_y = np.array(y_t[start:end])
                _, c = sess.run([optimizer, cost], feed_dict={x: batch_x, y: batch_y})
                epoch_loss += c
                i+=batch_size
            if epoch%100==0:
                print('Epoch', epoch, 'completed out of',hm_epochs,'loss:',epoch_loss)

        correct = tf.equal(tf.argmax(prediction, 1), tf.argmax(y, 1))

        accuracy = tf.reduce_mean(tf.cast(correct, 'float'))
        print('Accuracy:',accuracy.eval({x:X_test, y:y_te}))

train_neural_network(x)

('Epoch', 0, 'completed out of', 501, 'loss:', 5464.6685947179794)
('Epoch', 100, 'completed out of', 501, 'loss:', 588.5840830206871)
('Epoch', 200, 'completed out of', 501, 'loss:', 586.66650831699371)
('Epoch', 300, 'completed out of', 501, 'loss:', 585.73793029785156)
('Epoch', 400, 'completed out of', 501, 'loss:', 585.47006869316101)
('Epoch', 500, 'completed out of', 501, 'loss:', 585.38869827985764)
('Accuracy:', 0.72958392)


In [56]:
import tensorflow as tf
from tensorflow.contrib import rnn
epochs = 501
n_classes = 3
batch_size = 79
chunk_size = 17
n_chunks = 2
rnn_size = 122
#n_preds = None
x = tf.placeholder('float',[None,n_chunks,chunk_size])
y = tf.placeholder('float')
def recurrent_neural_network(x):
    layer = {'weights':tf.Variable(tf.random_normal([rnn_size,n_classes])),
             'biases':tf.Variable(tf.random_normal([n_classes]))}
    
    x = tf.unstack(x, n_chunks, 1)
    #print x.shape
    with tf.variable_scope('cell_def'):
        lstm_cell = tf.contrib.rnn.BasicLSTMCell(rnn_size)

    # Get lstm cell output
    with tf.variable_scope('rnnf_def'):
        outputs, states = rnn.static_rnn(lstm_cell, x, dtype=tf.float32)

    output = tf.matmul(outputs[-1],layer['weights']) + layer['biases']

    return output
def train_neural_network(x):
    prediction = recurrent_neural_network(x)
    cost = tf.reduce_mean( tf.nn.softmax_cross_entropy_with_logits(logits=prediction,labels=y) )
    optimizer = tf.train.AdamOptimizer(learning_rate=0.03,beta1=0.9,beta2=0.999,epsilon=1e-09,use_locking=True,name='Adam').minimize(cost)
    
    
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())

        for epoch in range(epochs):
            epoch_loss = 0
            i = 0
            while i<len(X_train):
                start = i
                end = i + batch_size
                #print(start,end)
                epoch_x, epoch_y = X_train[start:end],y_t[start:end]
                epoch_x = epoch_x.reshape((batch_size,n_chunks,chunk_size))
                #print epoch_x.shape
                _, c = sess.run([optimizer, cost], feed_dict={x: epoch_x, y: epoch_y})
                epoch_loss += c
                i += batch_size
            if epoch%100==0:
                print('Epoch', epoch, 'completed out of',epochs,'loss:',epoch_loss)

        correct = tf.equal(tf.argmax(prediction, 1), tf.argmax(y, 1))

        accuracy = tf.reduce_mean(tf.cast(correct, 'float'))
        print('Accuracy:',accuracy.eval({x:X_test.reshape((-1, n_chunks, chunk_size)), y:y_te}))
        pred = sess.run(prediction,feed_dict={x:X_test.reshape((-1, n_chunks, chunk_size))})
        corr = tf.argmax(pred,1)
        corr = sess.run(corr)
        #print(corr)
        #n_preds = corr
        #k = [i+1 for i in range(len(corr))]
        #yg = pd.DataFrame({'ImageId':pd.Series(k),'Label':pd.Series(corr)})
        #yg.to_csv('ans.csv',index=False)
        return pred,corr
y_score_rnn,pred_rnn = train_neural_network(x)

('Epoch', 0, 'completed out of', 501, 'loss:', 606.3062627017498)
('Epoch', 100, 'completed out of', 501, 'loss:', 515.94872909784317)
('Epoch', 200, 'completed out of', 501, 'loss:', 453.65660950541496)
('Epoch', 300, 'completed out of', 501, 'loss:', 410.71858951449394)
('Epoch', 400, 'completed out of', 501, 'loss:', 384.1917465031147)
('Epoch', 500, 'completed out of', 501, 'loss:', 360.53733158111572)
('Accuracy:', 0.8017146)
